### ISSUE TITLE
diyabc-rf does not load from R Studio

### ISSUE THREAD

**Issue by selasphoruskershaw** [diyabc/diyabcGUI#120] opened 2022-01-05 22:42 UTC
Hello,

After following the installation instructions, after using "diyabcGUI::diyabc()", the program quickly loads and then disappears.

I also get the following error messages in R (below). Any help would be appreciated. Thanks.

Listening on http://127.0.0.1:3346
This Font Awesome icon ('gear') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
The `name` provided ('circle-o-notch') is deprecated in Font Awesome 5:
* please consider using 'circle-notch' or 'fas fa-circle-notch' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
The `name` provided ('refresh') is deprecated in Font Awesome 5:
* please consider using 'sync' or 'fas fa-sync' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
Warning: Error in : Reactive context was created in one process and invalidated from another.
  [No stack trace available]

**Comment by vasotola** [comment] 2022-01-06 17:22
I am getting a similar error where the GUI shows up for a second, and then disappears.  It was working a few weeks ago, but just updated and reinstalled all the packages today. Below is the error output. Thanks!

> diyabcGUI::diyabc()

Listening on http://127.0.0.1:7255
This Font Awesome icon ('gear') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
The `name` provided ('circle-o-notch') is deprecated in Font Awesome 5:
* please consider using 'circle-notch' or 'fas fa-circle-notch' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
The `name` provided ('refresh') is deprecated in Font Awesome 5:
* please consider using 'sync' or 'fas fa-sync' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('warning') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
Warning: Error in <<-: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in <<-: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in <<-: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in <-: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval: object 'env' not found
  52: eval
  51: eval
  48: dotloop
  47: req
  46: observe
  45: <observer>
   2: shiny::runApp
   1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in <reactive>: object 'env' not found
  63: <reactive>
  47: project_dir
  46: observe
  45: <observer>
   2: shiny::runApp
   1: diyabcGUI::diyabc
Warning: Error in identical: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval: object 'env' not found
  52: eval
  51: eval
  48: dotloop
  47: req
  46: observe
  45: <observer>
   2: shiny::runApp
   1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval: object 'env' not found
  52: eval
  51: eval
  48: dotloop
  47: req
  46: observe
  45: <observer>
   2: shiny::runApp
   1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc
Warning: Error in eval_tidy: object 'env' not found
  2: shiny::runApp
  1: diyabcGUI::diyabc

**Comment by gdurif** [comment] 2022-01-07 14:05
Hi @selasphoruskershaw @vasotola 
Sorry for the trouble and thanks for the report. I am away from office until january 11th. I will look into this as soon as I get back.
Best,

**Comment by vasotola** [comment] 2022-01-11 17:57
Just tried to run the program through R and it worked! Did not get this same issue/error as I reported. FYI. Thanks!

**Comment by gdurif** [comment] 2022-01-17 13:35
Hi,
Thanks for the update. I'll do some other checks just in case.
Best,

**Comment by gdurif** [comment] 2022-02-19 09:15
Note:
- Problem with icons fixed by 491f594
- Unable to replicate problem with app environment

Closing

**Comment by jd-klein** [comment] 2022-02-23 06:08
I see this issue has been closed but I have the exact same problem including error message as @selasphoruskershaw first mentioned here. I've been using the program for a few weeks without issues, now since yesterday it shortly loads, then disappears. Is there a solution for this?

**Comment by gdurif** [comment] 2022-02-23 08:34
@jd-klein Could you tell me which version you are using ? on which OS ? Is it the latest release (from 2days ago) ?

**Comment by jd-klein** [comment] 2022-02-23 09:21
sorry, I should have double checked before I posted. I just updated the binary files and the issue is gone!

**Comment by gdurif** [comment] 2022-02-23 11:38
No problem :wink:

**Closed by gdurif** 2022-02-23 11:38 UTC
Labels: bug, to investigate, v1.1+, fixed, user feedback
