### ISSUE TITLE
Log file missing

### ISSUE THREAD

**Issue by EJFuchs** [diyabc/diyabcGUI#127] opened 2022-02-09 15:15 UTC
I installed the latest version  of diyabcGUI, tried to run the toy Microsatellite example and the application crashed during simulations. Now I  cannot run the package because of the following error:

`INFO [2022-02-09 09:09:27] log file: /var/folders/h0/7f985qrj10x3hww11vpq8w900000gp/T//Rtmpyi4hhz/diyabc_rf_gui.log
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/var/folders/h0/7f985qrj10x3hww11vpq8w900000gp/T//Rtmpyi4hhz/diyabc_rf_gui.log': No such file or directory`

Running on macOS latests update and Rstudio RStudio 2021.09.2+382 "Ghost Orchid"

**Comment by gdurif** [comment] 2022-02-10 14:43
Hi,
Thanks for the report, I'll look into that. I think the problem is that R remove the temp directory although the log file was still being used. I think there is a parameter to avoid this.
Thanks again and sorry for the trouble,
Best

**Comment by gdurif** [comment] 2022-02-10 14:57
Quitting and restarting RStudio does not change anything ?

**Comment by gdurif** [comment] 2022-02-17 14:18
Should be fixed by d4f7e65

**Comment by gdurif** [comment] 2022-02-21 07:17
Could you tell me if I can close this one? Thanks in advance, Best

**Closed** 2022-02-21 13:29 UTC
Labels: bug, to be validated, v1.1+, fixed, user feedback
